### PR TITLE
Add Content MathML annotations

### PR DESCRIPTION
**Pull request by bentley**
Demo of https://github.com/standardebooks/manual/pull/131.

I found ~~two~~ *three* modern ebooks that use epsilon instead of *e* in the denominator, including the PG Australia transcription; the audiobook narrated by John McDonough uses sigma for some reason. Whatever it is, [it certainly isn’t *e*](https://archive.org/details/lewis_arrowsmith_1925/page/406/mode/2up); I can believe that that scribble is an epsilon, and I can’t pull a sigma out of it no matter how I try, so epsilon it is.

### CODE REVIEW

**Comment by acabal** [comment]
OK I think this looks good. Are you interested in going through the corpus and updating any instances of content MathML? I don't think there's too many. The very math-heavy books like Tractatus actually have very little content MathML because most of it is basically inscrutable.

**Comment by acabal** [comment]
Also can you resolve these merge conflicts so I can merge it in?

**Comment by bentley** [comment]
Updated.

> Are you interested in going through the corpus and updating any instances of content MathML?

I would be, but are there any?

**Comment by acabal** [comment]
Huh, now that I look I guess there aren't. Problem solved, thanks! :)

**Pull request merged**
